model:
  device: "cuda"
  dtype: "float32"
  image_size: 224
  patch_size: 16
  in_channels: 3
  embed_dim: 384
  depth: 8
  num_heads: 6
  mlp_ratio: 4.0
  dropout: 0.1
  attention_dropout: 0.0
  num_classes: 10
  checkpoint_path: null

data:
  train_dir: "data/train"
  eval_dir: "data/eval"
  image_size: 224
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  augment: true
  num_workers: 4
  pin_memory: true

training:
  random_seed: 1337
  batch_size: 16
  micro_batch_size: 8
  num_mc_samples: 4
  num_train_steps: 1000
  learning_rate: 3.0e-4
  weight_decay: 0.05
  betas: [0.9, 0.999]
  max_grad_norm: 1.0
  ckpt_dir: "ckpt"
  log_dir: "logs"
  eval_interval: 50
  ckpt_save_interval: 200
  memory_efficient_adamw: true

