model:
  device: "cuda"
  dtype: "bfloat16"
  image_size: 256
  patch_size: 16
  in_channels: 3
  embed_dim: 512
  depth: 12
  num_heads: 8
  mlp_ratio: 4.0
  dropout: 0.1
  attention_dropout: 0.0
  num_classes: 100
  checkpoint_path: null

data:
  train_dir: "data/train"
  eval_dir: "data/eval"
  image_size: 256
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  augment: true
  num_workers: 8
  pin_memory: true

training:
  random_seed: 1337
  batch_size: 32
  micro_batch_size: 8
  num_mc_samples: 6
  num_train_steps: 2000
  learning_rate: 2.0e-4
  weight_decay: 0.05
  betas: [0.9, 0.999]
  max_grad_norm: 1.0
  ckpt_dir: "ckpt"
  log_dir: "logs"
  eval_interval: 50
  ckpt_save_interval: 200
  memory_efficient_adamw: true

